# Generated by Django 5.2 on 2025-04-11 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_contact_department_head'),
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.TextField(choices=[('APPR', 'Approved'), ('RJCT', 'Rejected'), ('PNDG', 'Pending')])),
                ('reason', models.TextField(blank=True, null=True)),
                ('closed', models.BooleanField(blank=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='company.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(choices=[('SEND', 'Sent to Supervisor'), ('CLSD', 'Closed')], max_length=100)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('supervisor_remarks', models.TextField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('leave_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leaveprocess')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_queries_sent', to=settings.AUTH_USER_MODEL)),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_queries_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
