# Generated by Django 5.2 on 2025-05-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorquery',
            name='leave_request',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_queries', to='leave.leaverequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveprocess',
            name='action_taken',
            field=models.CharField(choices=[('SEND', 'Sent to Supervisor'), ('CLSD', 'Closed'), ('APPR', 'Approved'), ('DCLN', 'Declined')], max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorquery',
            name='leave_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_queries', to='leave.leaveprocess'),
        ),
    ]
