# Generated by Django 5.2 on 2025-07-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_supervisorquery_leave_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='annual_entitlement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
