# Generated by Django 5.2 on 2025-04-16 10:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.JSONField(blank=True, default=core.models.default_contact, null=True),
        ),
    ]
