# Generated by Django 5.2 on 2025-04-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
