# Generated by Django 5.2 on 2025-04-11 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
