# Generated by Django 5.2 on 2025-04-16 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='work_end_time',
            field=models.TimeField(blank=True, default=datetime.time(5, 30), null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='work_start_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 30), null=True),
        ),
    ]
